CREATE DATABASE IF NOT EXISTS FROTA_VEICULOS;

USE FROTA_VEICULOS;

CREATE TABLE CAMINHAO (
   CODIGOC INT NOT NULL,
   MARCA VARCHAR(30) NOT NULL,
   MODELO VARCHAR(30) NOT NULL,
   PRIMARY KEY (CODIGOC)
);
CREATE TABLE PRODUTO (
   CODIGOP INT NOT NULL,
   MARCA VARCHAR(50) NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   FABRICANTE VARCHAR(50) NOT NULL,
   PRIMARY KEY (CODIGOP)
);
CREATE TABLE MOTORISTA (
	RG VARCHAR(15) NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    IDADE INT NOT NULL,
    ENDERECO VARCHAR(80) NOT NULL,
    PRIMARY KEY(RG)
);
CREATE TABLE VIAGEM (
	DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    RG VARCHAR(15) NOT NULL,
    CODIGOC INT NOT NULL,
    PRIMARY KEY (DATA_INICIO, RG, CODIGOC),
    FOREIGN KEY	(RG) REFERENCES MOTORISTA(RG)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(CODIGOC) REFERENCES CAMINHAO(CODIGOC)
    ON UPDATE CASCADE ON DELETE CASCADE
    );
CREATE TABLE TRANSPORTADORA(
	DATA_INICIO DATE NOT NULL,
    RG VARCHAR(15) NOT NULL,
    CODIGOC INT NOT NULL,
    CODIGOP INT NOT NULL,
    PRIMARY KEY(DATA_INICIO, RG, CODIGOC, CODIGOP),
    FOREIGN KEY(DATA_INICIO, RG, CODIGOC) REFERENCES VIAGEM(DATA_INICIO, RG, CODIGOC)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(CODIGOP) REFERENCES PRODUTO (CODIGOP)
    ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO CAMINHAO VALUES (1, 'MERCEDEZ', 'BW12');
INSERT INTO CAMINHAO VALUES (2, 'SCANIA', 'AD23');
INSERT INTO CAMINHAO VALUES (3, 'MERCEDEZ', 'TRUCK');
INSERT INTO CAMINHAO VALUES (4, 'FORD', 'ERON');
INSERT INTO CAMINHAO VALUES (5, 'SCANIA', 'THOR');	

/*SELECT DISTINCT SERVE PARA FILTAR ALGUM TIPO LETRA OU NOME DENTRO DA TABELA*/
SELECT DISTINCT MARCA
FROM CAMINHAO
WHERE MARCA LIKE '%C%';


INSERT INTO PRODUTO VALUES (1, 'SOIL', 'SOJA', 'SANTANDER');
INSERT INTO PRODUTO VALUES (2, 'GARLIC', 'ALHO', 'SANTANDER');
INSERT INTO PRODUTO VALUES (3, 'ONION', 'CEBOLA', 'CREMESP');
INSERT INTO PRODUTO VALUES (4, 'SALT', 'SAL', 'CREMESP');
INSERT INTO PRODUTO VALUES (5, 'OIL', 'AZEITE', 'GALO');

/*ESSE É PARA SELECIONAR O NUMERO DE PRODUTOS OU NUMERAR QUALQUER TIPO DE COISA QUE POSSUI REPETIÇÕES NA TABELA*/
SELECT FABRICANTE, COUNT(*)'NUMERO DE PRODUTOS'
FROM PRODUTO
WHERE FABRICANTE = 'CREMESP';

INSERT INTO MOTORISTA VALUES ('123', 'CARLA', 32, 'RUA SAO BENTO, 22');
INSERT INTO MOTORISTA VALUES ('234', 'ANTONIO', 40, 'RUA JOAQUIM BARBOSA, 21');
INSERT INTO MOTORISTA VALUES ('456', 'JOANA', 28, 'RUA AMARANTHUS, 43');
INSERT INTO MOTORISTA VALUES ('347', 'LUIZ', 21, 'RUA GHOST, 54');
INSERT INTO MOTORISTA VALUES ('555', 'TEREZA', 55, 'RUA THEODORO, 66');

INSERT INTO VIAGEM VALUES ('2020-04-12', '2020-05-15', '123', 1);
INSERT INTO VIAGEM VALUES ('2020-05-15', '2020-06-16', '123', 2);
INSERT INTO VIAGEM VALUES ('2020-05-31', NULL, '234', 2);
INSERT INTO VIAGEM VALUES ('2020-07-08', NULL, '456', 3);
INSERT INTO VIAGEM VALUES ('2020-08-15', NULL, '347', 3);

/*PARA SELECIONAR AS VIAGENS QUE NÃO FORAM CONCLUIDAS*/
SELECT * FROM VIAGEM
WHERE DATA_FIM IS NULL;

/*PARA SELECIONAR AS VIAGENS QUE FORAM CONCLUIDAS*/
SELECT * FROM VIAGEM
WHERE DATA_FIM IS TRUE;

/*PARA SELECIONAR DADOS DOS MOTORISTAS NAS VIAGENS*/
SELECT DATA_INICIO, DATA_FIM, NOME, IDADE, ENDERECO
FROM VIAGEM,MOTORISTA
WHERE VIAGEM.RG = MOTORISTA.RG;

/*PARA SELECIONAR OS DADOS DOS CAMINHÕES NA VIAGEM*/
SELECT DATA_INICIO,DATA_FIM,MARCA,MODELO
FROM VIAGEM,CAMINHAO
WHERE VIAGEM.CODIGOC = CAMINHAO.CODIGOC;

SELECT * FROM TRANSPORTADORA, VIAGEM, PRODUTO
WHERE TRANSPORTADORA.DATA_INICIO = VIAGEM.DATA_INICIO
AND TRANSPORTADORA.RG = VIAGEM.RG
AND TRANSPORTADORA.CODIGOC = VIAGEM.CODIGOC
AND TRANSPORTADORA.CODIGOP = PRODUTO.CODIGOP;


INSERT INTO TRANSPORTADORA VALUES ('2020-04-12', '123', 1, 1);
INSERT INTO TRANSPORTADORA VALUES ('2020-05-15', '123', 2, 2);
INSERT INTO TRANSPORTADORA VALUES ('2020-05-31', '234', 2, 3);
INSERT INTO TRANSPORTADORA VALUES ('2020-07-08', '456', 3, 4);
INSERT INTO TRANSPORTADORA VALUES ('2020-08-15', '347', 3, 5);


SHOW TABLES;




